# Generated by Django 4.2.4 on 2023-08-20 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_vehicleatrentalstation_rental_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleatrentalstation',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.rental'),
        ),
    ]
