from django.urls import path
from .views import (RentalListCreateAPIView,
                    RentalDetailAPIView,
                    CustomerListAPIView,
                    CustomerAddAPIView,
                    VehicleAddAPIView,
                    VehicleDetailAPIView,
                    VehicleListAPIView,
                    RentalStationListAPIView,
                    RentalStationAddAPIView,
                    RentalStationDetailAPIView,
                    VehicleDistributionStatsAPIView,
                    VehicleDistributionAPIView,
                    CustomerDetailAPIView,
                    MonthlyRentalStatsAPIView,
                    PopularRentalStationStatsAPIView,
                    MostRentedVehicleTypeAPIView,
                    )

urlpatterns = [
    path('rental/', RentalListCreateAPIView.as_view(), name='rental-list-create'),
    path('rental/<int:pk>/', RentalDetailAPIView.as_view(), name='rental-detail'),
    path('customer/', CustomerListAPIView.as_view(), name='customer-list'),
    path('customer/<int:id>/', CustomerDetailAPIView.as_view(), name='customer-detail'),
    path('customer/add/', CustomerAddAPIView.as_view(), name='customer-add'),
    path('vehicle/', VehicleListAPIView.as_view(), name='vehicle-list'),
    path('vehicle/<int:pk>/', VehicleDetailAPIView.as_view(), name='vehicle-detail'),
    path('vehicle/add/', VehicleAddAPIView.as_view(), name='vehicle-add'),
    path('station/', RentalStationListAPIView.as_view(), name='rental-station-list'),
    path('station/add/', RentalStationAddAPIView.as_view(), name='rental-station-add'),
    path('station/<int:station_id>/', RentalStationDetailAPIView.as_view(), name='rental-station-detail'),
    path('station/distribution/', VehicleDistributionStatsAPIView.as_view(), name='vehicle-distribution-stats'),
    path('station/distribute/', VehicleDistributionAPIView.as_view(), name='vehicle-distribution'),
    path('stats/monthly/', MonthlyRentalStatsAPIView.as_view(), name='monthly-stats'),
    path('rent/stats/popular_station/', PopularRentalStationStatsAPIView.as_view(), name='popular-station-stats'),
    path('rent/stats/popular_vehicle_type/', MostRentedVehicleTypeAPIView.as_view(), name='popular_vehicle_type'),
]
